### ISSUE TITLE
[Setting] kubeadm init error

### ISSUE THREAD

**Issue by deeev-sb** [ESE-Lab/Kubeflow#8]
kubeadm init 과정에서 error 발생하는데 
![Kubeflow_error](https://user-images.githubusercontent.com/46712693/83343523-99ac7880-a336-11ea-8156-2d8a67784291.png)
권한 문제인가 싶어서 root 로도 해봤는데 erorr나요
![Kubeflow_error_root](https://user-images.githubusercontent.com/46712693/83343540-ca8cad80-a336-11ea-9671-76300bea3406.PNG)
이미 존재하는 파일이여서 에러가 생기는 것 같은데 이 부분을 어떻게 하면 될까요?

**Comment by hochan222** [comment]
192.168.0.5 는 제 아이피인데 아이피한번확인해보세요 @Kim-SuBin

**Comment by deeev-sb** [comment]
제 아이피가 192.168.0.3인데 그걸로 해도 똑같아요…. 혹시나 하는 마음에 172.16.0.0/16도 다른 거로 바꿔봤는데 안돼요. ㅠㅠㅠ @hochan222

**Comment by hochan222** [comment]
그러면 다른게 틀렸나봐요..

**Comment by hochan222** [comment]
https://kangwoo.kr/category/machine-learning/kubeflow/
